site_name: Documentation
nav:
  - Get Started:
    - Overview: index.md
    - Installation: home/installation.md
  - Tutorial:
    - Pong 2D:
      - Overview: tutorial/Pong2D/overview.md
      - Get Started: tutorial/Pong2D/gameScene.md
      - Set Up The Scene: tutorial/Pong2D/setup.md
      - Declare Inputs for Your Game: tutorial/Pong2D/inputSettings.md
      - FrameSyncEngineController: tutorial/Pong2D/frameSyncEngineController.md
      - StaticFrameSyncBehaviour: tutorial/Pong2D/staticFrameSyncBehaviour.md
      - Ball Manager: tutorial/Pong2D/ballManager.md
      - Paddle Movement: tutorial/Pong2D/paddleMovement.md
      - Playing Offline: tutorial/Pong2D/playOffline.md
      - Playing Online: tutorial/Pong2D/playOnline.md
    - SocCar 3D:
      - Overview: tutorial/SocCar/overview.md
      - Get Started: tutorial/SocCar/getStarted.md
    - Pong Game:
      - Overview: tutorial/pong/overview.md
      - Physics 2D: tutorial/pong/parallel2d.md
      - Creating FrameSyncAgent: tutorial/pong/createAgent.md
      - Configuring FrameSyncEngine: tutorial/pong/configEngine.md
      - Configuring FrameSyncGame: tutorial/pong/configGame.md
      - Collecting Player Inputs: tutorial/pong/collectInput.md
      - StaticFrameSyncBehaviour: tutorial/pong/staticFrameSyncBehaviour.md
      - Paddle Owner: tutorial/pong/paddleOwner.md
      - Paddle Movement: tutorial/pong/paddleMovement.md
      - Paddle Position Data: tutorial/pong/paddlePosition.md
      - Ball Manager: tutorial/pong/ballManager.md
      - Playing Offline: tutorial/pong/offline.md
      - Debug Server: tutorial/pong/debugServer.md
      - Connecting to Debug Server: tutorial/pong/connectToDebugServer.md
      - Online FrameSyncAgent: tutorial/pong/online.md
      - Building the Game: tutorial/pong/buildGame.md
      - Frame Information: tutorial/pong/viewFrame.md
      - Rollback: tutorial/pong/Rollback.md
  - FrameSync:
    - Overview: frameSync/framesync.md
    - Deterministic: frameSync/deterministic.md
    - Input Settings: frameSync/InputSettings.md
    - Prefab Registry: frameSync/PrefabRegistry.md
    - FrameSyncEngine: 
      - FrameSyncEngineController: frameSync/frameSyncEngine/frameSyncEngineController.md
      - Offline Mode: frameSync/frameSyncEngine/offline.md
      - Online Mode: frameSync/frameSyncEngine/online.md
      - Rollback Mode: frameSync/frameSyncEngine/rollback.md
    - FrameSyncBehaviours: frameSync/frameSyncBehaviours.md
    - Game Logic: 
      - IFrameSyncStart: frameSync/GameLogic/IFrameSyncStart.md
      - IFrameSyncPlayerUpdate: frameSync/GameLogic/IFrameSyncPlayerUpdate.md
      - IFrameSyncComputerUpdate: frameSync/GameLogic/IFrameSyncComputerUpdate.md
    - Game States:
      - IFrameSyncDataContainer: frameSync/GameStates/IFrameSyncDataContainer.md
      - IFrameSyncSnapshot: frameSync/GameStates/IFrameSyncSnapshot.md
  - Physics2D:
    - Overview: physics2d/physics2D.md
    - Classes:
      - ParallelBoxCollider2D: physics2d/parallelBoxCollider2D.md
  - FixedMath:
    - Overview: fixedmath/fixedmath.md
    - Classes:
      - FMath: fixedmath/fmath.md
      - FVector2: fixedmath/fvector2.md
      - FVector3: fixedmath/fvector3.md
      - FQuaternion: fixedmath/fquaternion.md
      - FMatrix4x4: fixedmath/fmatrix4x4.md
    - Scripting:
      - FMath.Deg2Rad: fixedmath/reference/fmath-deg2rad.md
extra_css:
  - stylesheets/extra.css
theme:
  # logo: assets/logo-light.png
  favicon: assets/favicon.png
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
